[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd src/backend && python -m langflow run --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
